=== JanCzarnecki/mdk/CheMet/CheMet-IO/src/main/resources/uk/ac/ebi/io/xml/schema/chemet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://www.w3schools.com"
           targetNamespace="http://www.ebi.ac.uk/~johnmay/"
           elementFormDefault="qualified">

    <xs:element name="annotations">
        <xs:complexType>
            <xs:sequence>
                
                <xs:element name="simple-annotation">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="value" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="annotation-index" type="xs:byte" use="required"/>
                    </xs:complexType>
                </xs:element>

                <xs:element name="structure-annotation">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="mol" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="annotation-index" type="xs:byte" use="required"/>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="author-annotation">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="comment" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="annotation-index" type="xs:byte" use="required"/>
                    </xs:complexType>
                </xs:element>
                
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== JanCzarnecki/mdk/CheMet/CheMet-IO/src/test/resources/uk/ac/ebi/io/xml/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<annotations xmlns="http://www.ebi.ac.uk/~johnmay/"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.ebi.ac.uk/~johnmay/ chemet.xsd">
    <simple-annotation annotation-index="1">
        <value>ATP</value>
    </simple-annotation>
    <simple-annotation annotation-index="1">
        <value>Adeninosine Triphosphate</value>
    </simple-annotation>
    <author-annotation annotation-index="2">
        <name>johnmay</name>
        <comment>target compound</comment>
    </author-annotation>
</annotations>
